name: navi4all
description: ""
publish_to: 'none'
version: 0.0.2+10

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.2.3
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  maplibre_gl: ^0.22.0
  maps_toolkit: ^3.1.0
  matomo_tracker: ^6.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/stadt_kl_red.png
    - assets/stadt_kl_white.png
    - assets/base_map_light_thumbnail.png
    - assets/base_map_dark_thumbnail.png
    - assets/base_map_satellite_thumbnail.png
    - assets/user_position.png
    - assets/marker_walking.png
    - assets/marker_bus.png
    - assets/marker_train.png
    - assets/place_general.png
    - assets/place_vis_imp.png