name: smartroots
description: ""
publish_to: 'none'
version: 0.0.1+14

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  maplibre_gl: ^0.24.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  maps_launcher: ^3.0.0+1
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_polyline_points: ^3.1.0
  maps_toolkit: ^3.1.0
  flutter_tts: ^4.2.3
  matomo_tracker: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/parkstark_foreground.png
    - assets/p_reserviert.png
    - assets/parking_avbl_yes.png
    - assets/parking_avbl_no.png
    - assets/parking_avbl_unknown.png
    - assets/place.png
    - assets/user_position.png
    - assets/base_map_light_thumbnail.png
    - assets/base_map_dark_thumbnail.png
    - assets/base_map_satellite_thumbnail.png
